#!/usr/bin/env bash
# Script thats install load balancer HAProxy
apt-get -y update
apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_copy.cfg
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend  srv_web_01_02-frontend
        bind *:80
        mode http
        default_backend srv_web_01_02-backend
backend srv_web_01_02-backend
        balance roundrobin
        server 448303-web-01 34.229.66.77:80 check
        server 448303-web-02 18.209.225.222:80 check
EOF
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart